kong:
  image: littlebaydigital/kong:0.8.3
  ports:
  - 7946:7946/tcp
  - 7946:7946/udp
  - 8000:8000/tcp
  - 8001:8001/tcp
  - 8443:8443/tcp
  environment:
    CLUSTER_LISTEN: rancher
    DATABASE: postgres
    POSTGRES_HOST: ${postgres_host}
    POSTGRES_PORT: ${postgres_port}
    POSTGRES_USER: ${postgres_user}
    POSTGRES_PASSWORD: ${postgres_password}
    POSTGRES_DB: ${postgres_db}
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: no-link
  tty: true
  external_links:
    - ${database_link}:kong-database
no-link:
  net: none
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  entrypoint: /bin/true
  image: busybox
