kong:
  ports:
  - 7946:7946/tcp
  - 7946:7946/udp
  - 8000:8000/tcp
  - 8001:8001/tcp
  - 8443:8443/tcp
  environment:
    CLUSTER_LISTEN: rancher
    DATABASE: ${database}
    POSTGRES_HOST: ${postgres_host}
    POSTGRES_USER: ${postgres_user}
    POSTGRES_PASSWORD: ${postgres_password}
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.sidekicks: kong-conf
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  volumes_from:
    - kong-conf
  tty: true
  image: littlebaydigital/kong:0.8.0
kong-conf:
  net: none
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes:
    - /etc/kong
  entrypoint: /bin/true
  image: busybox