.catalog:
  name: Kong
  version: v0.8.3-postgres
  description: |
    Kong API Gateway
  minimum_rancher_version: v1.0.0
  maintainer: "Yun Zhi Lin<yun@yunspace.com>"
  uuid: kong-0
  questions:
    - variable: "database_link"
      description: "Link to Kong database service or stack"
      label: "Database link"
      type: "service"
      default: "no-link"
      required: true
    - variable: "postgres_host"
      description: "PostgreSQL Host Name"
      label: "PostgreSQL host:"
      required: true
      default: "kong-database"
      type: "string"
    - variable: "postgres_port"
      description: "PostgreSQL port"
      label: "PostgreSQL port:"
      required: true
      default: 5432
      type: int
    - variable: "postgres_db"
      description: "PostgreSQL database" 
      label: "Postgres database:"
      required: false
      default: "kong"
      type: "string"
    - variable: "postgres_user"
      description: "PostgreSQL username"
      label: "PostgreSQL username:"
      required: true
      default: "kong"
      type: "string"
    - variable: "postgres_password"
      description: "PostgreSQL password"
      label: "PostgreSQL password:"
      required: true
      default: "kong" 
      type: "string"
kong:
  retain_ip: true
  health_check:
    port: 8001
    interval: 5000
    unhealthy_threshold: 3
    request_line: 'GET /# HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 5000
