.catalog:
  name: Kong
  version: v0.8.3
  description: |
    Kong API Gateway
  minimum_rancher_version: v1.0.0
  maintainer: "Yun Zhi Lin<yun@yunspace.com>"
  uuid: kong-0
  questions:
    - variable: "db_type"
      label: "DB Type:"
      required: true
      type: enum
      options:
        - "postgres"
        - "canssandra"
    - variable: "db_host"
      description: "Either: PostgreSQL Host Name, Cassandra Contact Points or Rancher Service Link"
      label: "DB Host:"
      required: true
      type: "string"
    - variable: "db_port"
      description: "PostgreSQL only, not applicable for Cassandra"
      label: "PostgreSQL port:"
      default: 5432
      type: int
    - variable: "db_name"
      description: "Name of the database/keyspace" 
      label: "DB Name"
      required: false
      default: "kong"
      type: "string"
    - variable: "db_user"
      label: "DB Username:"
      required: true
      default: "kong"
      type: "string"
    - variable: "db_password"
      label: "DB password:"
      required: true
      default: "kong" 
      type: "string"
kong:
  retain_ip: true
  health_check:
    port: 8001
    interval: 5000
    unhealthy_threshold: 3
    request_line: 'GET /# HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 5000
